version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    volumes:
      - ./backend:/work

  web:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - 4433:443
    volumes:
      - ./backend/public:/work/public
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build:
      context: .
      dockerfile: ./infra/mysql/Dockerfile
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 33060:3306

volumes:
  db-store:
