version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    image: aws-test/app
    volumes:
      - ./backend:/work

  web:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    image: aws-test/web
    ports:
      - 8080:80
    volumes:
      - ./backend/public:/work/public
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
